name: Semantic Release 🚀
on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup NodeJS and npm
        uses: actions/setup-node@v3
        with:
          node-version: "lts/hydrogen"
          cache: "yarn"

      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: yarn semantic-release
        uses: borales/actions-yarn@v4
        env:
          GITHUB_TOKEN: ${{ secrets.NIBIBOT_GIT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          cmd: semantic-release
