name: ⛓️ Tests @nibiruchain/indexer-nibi

on:
  pull_request:
    branches: ["main", "releases/*"]
    paths: ["**.js", "**.ts", "**.tsx", "**.json"]
  push:
    branches: ["main", "releases/*"]
    paths: ["**.js", "**.ts", "**.tsx", "**.json"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  test-indexer-nibi:
    runs-on: ubuntu-latest
    env:
      CHAIN_HOST: ${{ secrets.CHAIN_HOST }}
      VALIDATOR_MNEMONIC: ${{ secrets.VALIDATOR_MNEMONIC }}
      VALIDATOR_ADDRESS: ${{ secrets.VALIDATOR_ADDRESS }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS and npm
        uses: actions/setup-node@v3
        with:
          node-version: "lts/hydrogen"
      - name: Install yarn using npm
        run: npm install -g yarn
      - name: Setup NodeJS with yarn caching
        uses: actions/setup-node@v3
        with:
          node-version: "lts/hydrogen"
          cache: "yarn"
      - name: Install dependencies
        run: yarn --prefer-offline --check-files
      - name: Build the application
        run: yarn build --scope @nibiruchain/indexer-nibi
      - name: Run tests - indexer-nibi
        run: yarn test:indexer-nibi

      # ---- Individual test flows: In the future, we can separate the
      # ---- e2e tests from the unit tests. Testing on a live chain poses challenges.
      # - name: test sdk.Dec conversions in the common package
      #   run: yarn test -t 'SdkDec'
      # - name: test node connections with http
      #   run: yarn test -t 'node connection'
      # - name: test cosmjs and nibiru queries
      #   run: yarn test -t 'test query module'
